import type { Metadata } from "next";
import "./globals.css";
import { poppinsFont } from "@/config/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            suppressHydrationWarning
            className={cn(
               "min-h-screen overflow-x-hidden bg-background text-foreground antialiased",
               poppinsFont.variable
            )}
         >
            {children}
         </body>
      </html>
   );
}
